version: '2'
services:
    dismarservices-app:
        image: dismarservices
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dismarservices-mysql:3306/dismarservices?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dismarservices-mysql:
        extends:
            file: mysql.yml
            service: dismarservices-mysql
